blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/HenriqZimer/dolphin-helm-chart/discussions
    about: For questions, use GitHub Discussions
  - name: Dolphin Docker Image Issues
    url: https://github.com/linuxserver/docker-dolphin/issues
    about: For issues with the linuxserver.io Dolphin image itself (not the Helm chart), use the official image repository
